//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjEasyDent.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdEasyDentEntities : DbContext
    {
        public bdEasyDentEntities()
            : base("name=bdEasyDentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAntecedente> tblAntecedentes { get; set; }
        public virtual DbSet<tblCita> tblCitas { get; set; }
        public virtual DbSet<tblHistorial> tblHistorials { get; set; }
        public virtual DbSet<tblOdontograma> tblOdontogramas { get; set; }
        public virtual DbSet<tblPaciente> tblPacientes { get; set; }
        public virtual DbSet<tblPatologia> tblPatologias { get; set; }
        public virtual DbSet<tblUsuario> tblUsuarios { get; set; }
    }
}
