//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjEasyDent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCita
    {
        public int id_cita { get; set; }
        public System.DateTime fecha_cita { get; set; }
        public string descripcion { get; set; }
        public int fk_odontologo { get; set; }
        public int fk_paciente { get; set; }
    
        public virtual tblPaciente tblPaciente { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
