//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjEasyDent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOdontograma
    {
        public int id_odontograma { get; set; }
        public System.DateTime fecha_odontograma { get; set; }
        public string d_18 { get; set; }
        public string d_17 { get; set; }
        public string d_16 { get; set; }
        public string d_15 { get; set; }
        public string d_14 { get; set; }
        public string d_13 { get; set; }
        public string d_12 { get; set; }
        public string d_11 { get; set; }
        public string d_21 { get; set; }
        public string d_22 { get; set; }
        public string d_23 { get; set; }
        public string d_24 { get; set; }
        public string d_25 { get; set; }
        public string d_26 { get; set; }
        public string d_27 { get; set; }
        public string d_28 { get; set; }
        public string d_55 { get; set; }
        public string d_54 { get; set; }
        public string d_53 { get; set; }
        public string d_52 { get; set; }
        public string d_51 { get; set; }
        public string d_61 { get; set; }
        public string d_62 { get; set; }
        public string d_63 { get; set; }
        public string d_64 { get; set; }
        public string d_65 { get; set; }
        public string d_38 { get; set; }
        public string d_37 { get; set; }
        public string d_36 { get; set; }
        public string d_35 { get; set; }
        public string d_34 { get; set; }
        public string d_33 { get; set; }
        public string d_32 { get; set; }
        public string d_31 { get; set; }
        public string d_41 { get; set; }
        public string d_42 { get; set; }
        public string d_43 { get; set; }
        public string d_44 { get; set; }
        public string d_45 { get; set; }
        public string d_46 { get; set; }
        public string d_47 { get; set; }
        public string d_48 { get; set; }
        public string d_75 { get; set; }
        public string d_74 { get; set; }
        public string d_73 { get; set; }
        public string d_72 { get; set; }
        public string d_71 { get; set; }
        public string d_81 { get; set; }
        public string d_82 { get; set; }
        public string d_83 { get; set; }
        public string d_84 { get; set; }
        public string d_85 { get; set; }
        public int fk_historial { get; set; }
    
        public virtual tblHistorial tblHistorial { get; set; }
    }
}
