//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjEasyDent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUsuario()
        {
            this.tblCitas = new HashSet<tblCita>();
            this.tblPacientes = new HashSet<tblPaciente>();
        }
    
        public int id_usuario { get; set; }
        public string tipo_documento { get; set; }
        public string numero_documento { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string titulos { get; set; }
        public string direccion_consultorio { get; set; }
        public string direccion_hogar { get; set; }
        public string telefono_consultorio { get; set; }
        public string telefono_personal { get; set; }
        public string email { get; set; }
        public int estado { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCita> tblCitas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPaciente> tblPacientes { get; set; }
    }
}
